export const posts = [
  {
    id: 1,
    username: "RohanSharma",
    dateOfPost: "2025-09-20T10:15:00Z",
    mainContent: "Just completed my IoT project with ESP32 for water quality monitoring. 🚰🔥",
    upvotes: 124,
    tags: ["IoT", "ESP32", "WaterMonitoring", "Project"],
    comments: [
      {
        id: 1,
        username: "TechEnthusiast",
        content: "That’s awesome! Did you use Firebase or MQTT for data transfer?",
        likes: 10,
        postTime: "2025-09-20T11:00:00Z",
      },
      {
        id: 2,
        username: "MCAStudent",
        content: "Great work! Can you share the circuit diagram?",
        likes: 7,
        postTime: "2025-09-20T11:30:00Z",
      },
    ],
  },
  {
    id: 2,
    username: "PriyaVerma",
    dateOfPost: "2025-09-19T08:45:00Z",
    mainContent: "Started exploring Next.js with Tailwind CSS. Loving the developer experience 💻✨",
    upvotes: 89,
    tags: ["Next.js", "TailwindCSS", "Frontend", "React"],
    comments: [
      {
        id: 1,
        username: "FrontendDev",
        content: "Next.js + Tailwind is a killer combo, you’ll love it!",
        likes: 14,
        postTime: "2025-09-19T09:10:00Z",
      },
      {
        id: 2,
        username: "CodeWizard",
        content: "Try adding shadcn/ui too, it makes UI development super fast.",
        likes: 6,
        postTime: "2025-09-19T09:40:00Z",
      },
    ],
  },
  {
    id: 3,
    username: "AmitKumar",
    dateOfPost: "2025-09-18T15:20:00Z",
    mainContent: "Operations Research assignment was tough today 😅 anyone solved the simplex problem?",
    upvotes: 42,
    tags: ["OperationsResearch", "Assignments", "MCA"],
    comments: [
      {
        id: 1,
        username: "MathGeek",
        content: "Yes, I solved it! The optimal solution had Z = 420.",
        likes: 8,
        postTime: "2025-09-18T15:50:00Z",
      },
      {
        id: 2,
        username: "RohanSharma",
        content: "Can you share the step-by-step simplex table?",
        likes: 5,
        postTime: "2025-09-18T16:15:00Z",
      },
    ],
  },
  {
    id: 4,
    username: "NehaSingh",
    dateOfPost: "2025-09-17T18:10:00Z",
    mainContent: "Just deployed my first full-stack app using Supabase 🚀🔥",
    upvotes: 77,
    tags: ["Supabase", "Postgres", "Fullstack"],
    comments: [
      {
        id: 1,
        username: "CloudGuy",
        content: "Supabase is really a Firebase alternative. How was the auth setup?",
        likes: 9,
        postTime: "2025-09-17T18:40:00Z",
      },
    ],
  },
  {
    id: 5,
    username: "VikramPatel",
    dateOfPost: "2025-09-16T09:50:00Z",
    mainContent: "Working on a facial recognition attendance system for college 🏫📸",
    upvotes: 65,
    tags: ["AI", "OpenCV", "AttendanceSystem"],
    comments: [
      {
        id: 1,
        username: "DeepLearner",
        content: "Did you use Haar cascades or a DNN model?",
        likes: 4,
        postTime: "2025-09-16T10:15:00Z",
      },
    ],
  },
  {
    id: 6,
    username: "AnjaliGupta",
    dateOfPost: "2025-09-15T20:05:00Z",
    mainContent: "UI/UX design matters as much as backend logic. Just redesigned my blog 💅",
    upvotes: 110,
    tags: ["UIUX", "Design", "Blog"],
    comments: [
      {
        id: 1,
        username: "CreativeCoder",
        content: "Totally agree! Design is the first impression.",
        likes: 12,
        postTime: "2025-09-15T20:30:00Z",
      },
    ],
  },
  {
    id: 7,
    username: "ArjunYadav",
    dateOfPost: "2025-09-14T14:00:00Z",
    mainContent: "Exploring Machine Learning with scikit-learn 📊",
    upvotes: 53,
    tags: ["ML", "ScikitLearn", "AI"],
    comments: [
      {
        id: 1,
        username: "DataNerd",
        content: "Try random forests, they’re powerful and easy to tune.",
        likes: 3,
        postTime: "2025-09-14T14:40:00Z",
      },
    ],
  },
  {
    id: 8,
    username: "KavitaMehta",
    dateOfPost: "2025-09-13T11:45:00Z",
    mainContent: "Dockerizing my Node.js app was a great learning experience 🐳",
    upvotes: 95,
    tags: ["Docker", "DevOps", "Node.js"],
    comments: [
      {
        id: 1,
        username: "OpsGuy",
        content: "Once you get used to Docker, deploying anywhere is a breeze.",
        likes: 11,
        postTime: "2025-09-13T12:20:00Z",
      },
    ],
  },
  {
    id: 9,
    username: "RahulVerma",
    dateOfPost: "2025-09-12T16:25:00Z",
    mainContent: "Just cleared AWS Certified Cloud Practitioner ☁️🎉",
    upvotes: 132,
    tags: ["AWS", "Cloud", "Certification"],
    comments: [
      {
        id: 1,
        username: "CloudLearner",
        content: "Congrats! Are you going for Solutions Architect next?",
        likes: 15,
        postTime: "2025-09-12T17:00:00Z",
      },
    ],
  },
  {
    id: 10,
    username: "SnehaRoy",
    dateOfPost: "2025-09-11T08:10:00Z",
    mainContent: "Learning DSA in Java. Any tips to stay consistent?",
    upvotes: 47,
    tags: ["DSA", "Java", "CodingPractice"],
    comments: [
      {
        id: 1,
        username: "AlgoMaster",
        content: "LeetCode daily challenges help a lot!",
        likes: 7,
        postTime: "2025-09-11T09:00:00Z",
      },
    ],
  },
  {
    id: 11,
    username: "ManishTiwari",
    dateOfPost: "2025-09-10T13:30:00Z",
    mainContent: "Just discovered Zustand for state management in React ⚛️",
    upvotes: 72,
    tags: ["React", "Zustand", "Frontend"],
    comments: [
      {
        id: 1,
        username: "ReactFan",
        content: "So much simpler than Redux!",
        likes: 9,
        postTime: "2025-09-10T14:00:00Z",
      },
    ],
  },
  {
    id: 12,
    username: "PoojaShah",
    dateOfPost: "2025-09-09T07:20:00Z",
    mainContent: "GraphQL APIs are so flexible compared to REST 🎯",
    upvotes: 68,
    tags: ["GraphQL", "API", "Backend"],
    comments: [
      {
        id: 1,
        username: "APIDev",
        content: "Yes! Queries save a lot of bandwidth.",
        likes: 6,
        postTime: "2025-09-09T07:50:00Z",
      },
    ],
  },
  {
    id: 13,
    username: "SaurabhMishra",
    dateOfPost: "2025-09-08T21:10:00Z",
    mainContent: "Started learning C# with .NET for enterprise apps 💼",
    upvotes: 59,
    tags: [".NET", "CSharp", "Enterprise"],
    comments: [
      {
        id: 1,
        username: "DotNetGuy",
        content: "Entity Framework is a lifesaver for DB stuff.",
        likes: 5,
        postTime: "2025-09-08T21:40:00Z",
      },
    ],
  },
  {
    id: 14,
    username: "DivyaKapoor",
    dateOfPost: "2025-09-07T18:00:00Z",
    mainContent: "Just made my first React Native app 📱",
    upvotes: 101,
    tags: ["ReactNative", "MobileApp", "CrossPlatform"],
    comments: [
      {
        id: 1,
        username: "MobileDev",
        content: "Nice! Did you try Expo or CLI?",
        likes: 8,
        postTime: "2025-09-07T18:30:00Z",
      },
    ],
  },
  {
    id: 15,
    username: "RitikaAgarwal",
    dateOfPost: "2025-09-06T09:45:00Z",
    mainContent: "Practicing SQL queries for database management 💾",
    upvotes: 36,
    tags: ["SQL", "Database", "DBMS"],
    comments: [
      {
        id: 1,
        username: "DBPro",
        content: "Don’t forget to learn indexing for performance!",
        likes: 3,
        postTime: "2025-09-06T10:20:00Z",
      },
    ],
  },
  {
    id: 16,
    username: "HarshVardhan",
    dateOfPost: "2025-09-05T14:30:00Z",
    mainContent: "AI chatbots are becoming super realistic 🤖",
    upvotes: 140,
    tags: ["AI", "Chatbot", "NLP"],
    comments: [
      {
        id: 1,
        username: "AIEnthusiast",
        content: "Yep, GPT-based ones are mind-blowing.",
        likes: 12,
        postTime: "2025-09-05T15:00:00Z",
      },
    ],
  },
  {
    id: 17,
    username: "KaranJain",
    dateOfPost: "2025-09-04T11:25:00Z",
    mainContent: "Debugging in VS Code feels like cheating 😅",
    upvotes: 81,
    tags: ["VSCode", "Debugging", "Tools"],
    comments: [
      {
        id: 1,
        username: "CodeHelper",
        content: "Breakpoints are lifesavers!",
        likes: 4,
        postTime: "2025-09-04T11:50:00Z",
      },
    ],
  },
  {
    id: 18,
    username: "MeenaJoshi",
    dateOfPost: "2025-09-03T17:40:00Z",
    mainContent: "Blockchain isn’t just crypto. Exploring supply chain use cases ⛓️",
    upvotes: 63,
    tags: ["Blockchain", "SupplyChain", "Web3"],
    comments: [
      {
        id: 1,
        username: "CryptoDev",
        content: "Smart contracts make it so transparent.",
        likes: 6,
        postTime: "2025-09-03T18:00:00Z",
      },
    ],
  },
  {
    id: 19,
    username: "AlokPandey",
    dateOfPost: "2025-09-02T10:00:00Z",
    mainContent: "Started exploring system design concepts. Scaling is tricky! ⚡",
    upvotes: 92,
    tags: ["SystemDesign", "Scalability", "Backend"],
    comments: [
      {
        id: 1,
        username: "ArchGuru",
        content: "Focus on caching & load balancers early.",
        likes: 9,
        postTime: "2025-09-02T10:40:00Z",
      },
    ],
  },
  {
    id: 20,
    username: "SunitaNair",
    dateOfPost: "2025-09-01T08:15:00Z",
    mainContent: "First hackathon experience was amazing 💡👩‍💻",
    upvotes: 118,
    tags: ["Hackathon", "Coding", "Teamwork"],
    comments: [
      {
        id: 1,
        username: "HackDev",
        content: "Congrats! Did your team win any prize?",
        likes: 11,
        postTime: "2025-09-01T09:00:00Z",
      },
    ],
  },
];
