import { type Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "./components/theme-provider";
import Script from "next/script";
import localFont from 'next/font/local'
export const metadata: Metadata = {
  title: "RoboZoneX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <ClerkProvider>
        <html lang="en">
          <body
            className={`antialiased overflow-x-hidden`}
          >
            {children}
             <Script
              src="https://www.googletagmanager.com/gtag/js?id=GA_TRACKING_ID"
              strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive">
              {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', 'GA_TRACKING_ID');
              `}
            </Script>
          </body>
        </html>
      </ClerkProvider>
    </ThemeProvider>
  );
}
